Module8 task1
htmlacademy-javascript/1518567-keksobooking-23 pull request #7
Opened 2021-07-01 09:11 UTC by NShatov

2021-07-01 09:13 UTC, NShatov commented
Попробовал несколько вариантов для валидации полей. Нашел в интернете несколько вариантов сопоставления полей в селекте, попробовал применить в своем проекте

2021-07-02 04:56 UTC, 4err requested changes

2021-07-02 04:56 UTC, 4err commented on js/form.js
> +    formTitle.setCustomValidity('Братан! Напиши пару строк от души!');
Давай все-таки писать тексты для пользователей, а не братанов :)

2021-07-02 04:56 UTC, 4err commented on js/form.js
> +    formTitle.setCustomValidity('');
Такой подход нужно комбинировать с проверкой в режиме реального времени или при нажатии на отправить, запускать новую проверку, т.к. в текущем варианте при введении правильного варианта после неправильного, необходимо еще раз нажать кнопку, чтобы все ушло. Кастомная валидация не сбрасывается.

2021-07-02 04:56 UTC, 4err commented on js/form.js
> +/*formRooms.addEventListener('onchange', getMatchingSelect(formRooms, formCapacity));*/
По сути эти 2 функции почти одно и то же. Оба варианта подходят, но в первом нужно использовать перебор в цикле и сравнивание значений, а не вручную прописывать все блоки.

2021-07-04 07:03 UTC, merged